name: vectortiles
version: '1.4.0'
synopsis: GIS Vector Tiles, as defined by Mapbox.
description: ! 'GIS Vector Tiles, as defined by Mapbox.

  This library implements version 2.1 of the official Mapbox spec, as defined

  here: <https://github.com/mapbox/vector-tile-spec/tree/master/2.1>


  Note that currently this library ignores top-level protobuf extensions,

  /Value/ extensions, and /UNKNOWN/ geometries.'
category: Geography
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3
homepage: https://github.com/fosskers/vectortiles

extra-source-files:
  - test/roads.mvt
  - test/onepoint.mvt
  - test/linestring.mvt
  - test/polygon.mvt
  - test/clearlake.mvt
  - README.md
  - CHANGELOG.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns

dependencies:
  - base >=4.9 && <4.12
  - bytestring
  - containers
  - hashable
  - mtl
  - protocol-buffers >= 2.4 && < 2.5
  - protocol-buffers-descriptor >= 2.4 && < 2.5
  - text >=1.2 && <1.3
  - unordered-containers
  - vector >=0.11 && <0.13

library:
  source-dirs: lib
  exposed-modules:
    - Geography.VectorTile
    - Geography.VectorTile.Internal
  dependencies:
    - deepseq >=1.4 && <1.5
    - transformers >=0.5 && <0.6

tests:
  vectortiles-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - hex >=0.1 && <0.2
      - tasty >=0.10.1.2
      - tasty-hunit >=0.9.2
      - vectortiles

benchmarks:
  vectortiles-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      # - -prof
      # - -fprof-auto
    dependencies:
      - criterion >=1.1 && <1.6
      - microlens >=0.4 && <0.5
      - microlens-platform >=0.3 && <0.4
      - random == 1.1.*
      - vectortiles
